import csv
from datetime import datetime, timezone
from decimal import Decimal
from pathlib import Path

import pytest

from primatis_data_seeding.generation.scenarios import ScenarioSettings
from primatis_data_seeding.pipeline.full_scenarios import (
    build_full_scenarios,
    load_copies_csv,
)


SETTINGS = ScenarioSettings(
    loan_duration_days=21,
    reservation_ready_hold_hours=48,
    loan_due_soon_days=3,
    fine_weekly_rate=Decimal("0.80"),
    fine_max_amount=Decimal("25.00"),
)
REFERENCE = datetime(2026, 9, 12, 12, tzinfo=timezone.utc)


def _write_copies_csv(path: Path, *, single_titles: int, multi_titles: int) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=(
                "title_source_key", "inventory_code", "location",
                "copy_condition", "availability_status",
            ),
        )
        writer.writeheader()
        for i in range(1, single_titles + 1):
            writer.writerow({
                "title_source_key": f"/books/S{i:04d}",
                "inventory_code": f"PRI-C-S{i:04d}-01",
                "location": "RDC-A01-E01",
                "copy_condition": "GOOD",
                "availability_status": "AVAILABLE",
            })
        for i in range(1, multi_titles + 1):
            for ordinal in (1, 2):
                writer.writerow({
                    "title_source_key": f"/books/M{i:04d}",
                    "inventory_code": f"PRI-C-M{i:04d}-{ordinal:02d}",
                    "location": "RDC-A01-E01",
                    "copy_condition": "GOOD",
                    "availability_status": "AVAILABLE",
                })


def _write_bpost_csv(path: Path) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=("postal_code", "locality"))
        writer.writeheader()
        for code, name in (("1000", "Bruxelles"), ("4000", "Liège"), ("9000", "Gent")):
            writer.writerow({"postal_code": code, "locality": name})


def test_load_copies_csv_round_trips(tmp_path: Path) -> None:
    copies_csv = tmp_path / "copies.csv"
    _write_copies_csv(copies_csv, single_titles=5, multi_titles=2)

    rows = load_copies_csv(copies_csv)

    assert len(rows) == 5 + 2 * 2
    assert all(row.copy_condition == "GOOD" for row in rows)
    assert all(row.availability_status == "AVAILABLE" for row in rows)


def test_load_copies_csv_rejects_missing_file(tmp_path: Path) -> None:
    with pytest.raises(ValueError):
        load_copies_csv(tmp_path / "missing.csv")


def _build(tmp_path: Path, *, seed: int = 1651) -> tuple[Path, dict]:
    tmp_path.mkdir(parents=True, exist_ok=True)
    copies_csv = tmp_path / "copies.csv"
    bpost_csv = tmp_path / "bpost_localities.csv"
    _write_copies_csv(copies_csv, single_titles=150, multi_titles=30)
    _write_bpost_csv(bpost_csv)

    output_dir = tmp_path / "output"
    report = build_full_scenarios(
        copies_csv=copies_csv,
        bpost_csv=bpost_csv,
        output_dir=output_dir,
        seed=seed,
        user_count=300,
        reference_datetime=REFERENCE,
        raw_password="a-fake-but-long-enough-password",
        settings=SETTINGS,
    )
    return output_dir, report


def test_build_full_scenarios_produces_expected_volumes(tmp_path: Path) -> None:
    output_dir, report = _build(tmp_path)

    assert report["scenarios"]["enabled"] is True
    assert report["scenarios"]["loans"] == 80 + 20 + 60
    assert report["scenarios"]["reservations"] == 40 + 20
    assert report["scenarios"]["fines"] == 60
    assert report["users"]["count"] == 300

    for name in ("users.csv", "addresses.csv", "residences.csv", "bpost_localities.csv",
                 "loans.csv", "reservations.csv", "fines.csv", "notifications.csv",
                 "copy_states.csv", "scenarios_build_report.json"):
        assert (output_dir / name).is_file()


def _read_rows_without_password_hash(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    for row in rows:
        row.pop("password_hash", None)
    return rows


def test_build_full_scenarios_is_deterministic(tmp_path: Path) -> None:
    # BCrypt salts are randomly generated by design (never seeded) — every
    # other field must still be strictly identical across two runs with
    # the same seed/reference_datetime/inputs.
    output_dir_a, report_a = _build(tmp_path / "a", seed=1651)
    output_dir_b, report_b = _build(tmp_path / "b", seed=1651)

    for name in ("loans.csv", "reservations.csv", "fines.csv", "notifications.csv",
                 "addresses.csv", "residences.csv"):
        content_a = (output_dir_a / name).read_text(encoding="utf-8")
        content_b = (output_dir_b / name).read_text(encoding="utf-8")
        assert content_a == content_b, f"{name} differs between two identical runs"

    assert _read_rows_without_password_hash(
        output_dir_a / "users.csv"
    ) == _read_rows_without_password_hash(output_dir_b / "users.csv")

    assert report_a["users"] == report_b["users"]
    assert report_a["scenarios"] == report_b["scenarios"]


def test_build_full_scenarios_different_seed_changes_output(tmp_path: Path) -> None:
    output_dir_a, _ = _build(tmp_path / "a", seed=1651)
    output_dir_b, _ = _build(tmp_path / "b", seed=9999)

    rows_a = _read_rows_without_password_hash(output_dir_a / "users.csv")
    rows_b = _read_rows_without_password_hash(output_dir_b / "users.csv")
    assert rows_a != rows_b


def test_build_full_scenarios_rejects_naive_datetime(tmp_path: Path) -> None:
    copies_csv = tmp_path / "copies.csv"
    bpost_csv = tmp_path / "bpost_localities.csv"
    _write_copies_csv(copies_csv, single_titles=150, multi_titles=30)
    _write_bpost_csv(bpost_csv)

    with pytest.raises(ValueError):
        build_full_scenarios(
            copies_csv=copies_csv,
            bpost_csv=bpost_csv,
            output_dir=tmp_path / "output",
            seed=1,
            user_count=300,
            reference_datetime=datetime(2026, 9, 12, 12),
            raw_password="a-fake-but-long-enough-password",
            settings=SETTINGS,
        )
