package be.primatis.article;

import org.springframework.stereotype.Component;

import java.text.Normalizer;
import java.util.Objects;
import java.util.function.Predicate;
import java.util.regex.Pattern;

/**
 * Génération du slug public d'un {@code Article} (DEV-11.4,
 * business-rules.md §7.8 : « required, unique, generated by backend,
 * stable »). Composant technique pur — ne connaît ni {@code
 * ArticleRepository}, ni l'authentification, ni la publication/
 * l'archivage ; la vérification d'unicité réelle est déléguée à un
 * {@link Predicate} fourni par l'appelant (voir {@link #generateUniqueSlug},
 * jamais une dépendance directe au Repository — garde ce composant
 * testable sans Spring/PostgreSQL, mission DEV-11.4 §9 : « ne pas
 * transformer le slug helper en mini-Service métier »).
 *
 * <p>Deux responsabilités volontairement séparées en deux méthodes
 * publiques indépendamment testables (mission §9) :
 * <ul>
 *   <li>{@link #normalize(String)} — normalisation pure, déterministe,
 *   sans effet de bord ;</li>
 *   <li>{@link #generateUniqueSlug(String, Predicate)} — résolution de
 *   collision par suffixe déterministe, à partir d'un test d'existence
 *   fourni par l'appelant.</li>
 * </ul>
 *
 * <p><b>Stabilité (SOURCE EXPLICITE, business-rules.md §7.8)</b> : ce
 * composant n'est destiné qu'à la création d'un Article. Une modification
 * ultérieure du titre ne doit jamais déclencher un nouvel appel à ce
 * composant — {@code UpdateArticleRequest} (DEV-11.3) ne porte d'ailleurs
 * aucun champ {@code slug}, seul le futur workflow de création
 * (DEV-11.5+) doit invoquer {@link #generateUniqueSlug}.
 */
@Component
public class ArticleSlugGenerator {

    /**
     * {@code article.slug VARCHAR(255)} (V001). Le slug de base est
     * tronqué à {@value #MAX_BASE_SLUG_LENGTH} caractères — IMPLEMENTATION
     * FREEDOM (aucune source ne fixe cette marge), choisie pour laisser une
     * place large et suffisante à un suffixe de collision déterministe
     * ({@code "-2"} à {@code "-999999"}) sans jamais dépasser la colonne
     * réelle. Aucune limite arbitraire n'est appliquée à {@code title}
     * lui-même (déjà borné à 255 caractères par {@code
     * CreateArticleRequest}, DEV-11.3).
     */
    static final int MAX_BASE_SLUG_LENGTH = 240;

    /**
     * Garde-fou technique contre une boucle infinie en cas de {@link
     * Predicate} défaillant — jamais atteignable en usage normal (même
     * principe défensif que {@code MAX_ASSIGNMENT_ATTEMPTS}/{@code
     * ReservationAssignmentService}, DEV-08.6), jamais une règle métier.
     */
    static final int MAX_SUFFIX_ATTEMPTS = 1000;

    private static final Pattern COMBINING_MARKS = Pattern.compile("\\p{M}+");
    private static final Pattern NON_ALPHANUMERIC_RUN = Pattern.compile("[^a-z0-9]+");
    private static final Pattern LEADING_OR_TRAILING_HYPHENS = Pattern.compile("^-+|-+$");

    /**
     * Normalisation pure : minuscules (locale-indépendant), suppression
     * des diacritiques (translittération ASCII via décomposition Unicode
     * NFD, ex. {@code "été"} → {@code "ete"}), toute suite de caractères
     * non alphanumériques réduite à un unique tiret, tirets de tête/fin
     * supprimés, résultat tronqué à {@link #MAX_BASE_SLUG_LENGTH}
     * caractères (avec un nouveau nettoyage des tirets de fin introduits
     * par la troncature).
     *
     * @throws NullPointerException     si {@code title} est {@code null}
     * @throws IllegalArgumentException si la normalisation produit une
     *         chaîne vide (ex. {@code "!!!"}, {@code "---"}, {@code "   "})
     *         — IMPLEMENTATION FREEDOM (mission DEV-11.4 §11) : rejet
     *         technique explicite plutôt qu'un repli déterministe
     *         générique ou, a fortiori, un identifiant aléatoire (exclu
     *         par la mission). Laisse au futur appelant la décision métier
     *         de refuser un tel titre.
     */
    public String normalize(String title) {
        Objects.requireNonNull(title, "title");

        String lowerCased = title.trim().toLowerCase(java.util.Locale.ROOT);
        String decomposed = Normalizer.normalize(lowerCased, Normalizer.Form.NFD);
        String withoutDiacritics = COMBINING_MARKS.matcher(decomposed).replaceAll("");
        String hyphenated = NON_ALPHANUMERIC_RUN.matcher(withoutDiacritics).replaceAll("-");
        String trimmedHyphens = LEADING_OR_TRAILING_HYPHENS.matcher(hyphenated).replaceAll("");

        String truncated = trimmedHyphens.length() > MAX_BASE_SLUG_LENGTH
                ? trimmedHyphens.substring(0, MAX_BASE_SLUG_LENGTH)
                : trimmedHyphens;
        String result = LEADING_OR_TRAILING_HYPHENS.matcher(truncated).replaceAll("");

        if (result.isEmpty()) {
            throw new IllegalArgumentException(
                    "La normalisation du titre '%s' produit un slug vide.".formatted(title));
        }
        return result;
    }

    /**
     * Résout la collision par suffixe déterministe : {@code "mon-article"},
     * puis {@code "mon-article-2"}, {@code "mon-article-3"}, ... jusqu'au
     * premier candidat pour lequel {@code slugExists} retourne
     * {@code false} (business-rules.md §7.8). {@code slugExists} est
     * typiquement {@code slug -> articleRepository.findBySlug(slug).isPresent()}
     * côté appelant — ce composant n'accède jamais lui-même au Repository.
     *
     * <p><b>Concurrence (mission DEV-11.4 §13)</b> : ce test d'existence
     * n'offre aucune garantie contre une collision entre deux créations
     * concurrentes calculant simultanément le même candidat — seule la
     * contrainte {@code uq_article_slug} (V001) reste l'autorité finale.
     * La stratégie de résolution d'un conflit détecté à l'écriture (retry
     * complet vs traduction d'erreur) appartient au futur
     * {@code ArticleService} et reste une IMPLEMENTATION FREEDOM, non
     * tranchée ici.
     *
     * @throws IllegalStateException si {@link #MAX_SUFFIX_ATTEMPTS} est
     *         atteint sans trouver de candidat libre (garde-fou technique,
     *         jamais atteignable en usage normal).
     */
    public String generateUniqueSlug(String title, Predicate<String> slugExists) {
        Objects.requireNonNull(slugExists, "slugExists");
        String base = normalize(title);

        if (!slugExists.test(base)) {
            return base;
        }
        for (int suffix = 2; suffix <= MAX_SUFFIX_ATTEMPTS; suffix++) {
            String candidate = base + "-" + suffix;
            if (!slugExists.test(candidate)) {
                return candidate;
            }
        }
        throw new IllegalStateException(
                "Impossible de résoudre un slug unique pour '%s' après %d tentatives."
                        .formatted(title, MAX_SUFFIX_ATTEMPTS));
    }
}
